version: 2.1

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

install_system_deps: &install_system_deps
  run:
    name: Install system dependencies
    command: |
      apk add build-base

defaults: &defaults
  working_directory: ~/repo

jobs:
  build_elixir_1_17_otp_27:
    docker:
      - image: hexpm/elixir:1.17.2-erlang-27.0.1-alpine-3.20.1
    <<: *defaults
    steps:
      - <<: *install_system_deps
      - checkout
      - <<: *install_hex_rebar
      - restore_cache:
          keys:
            - v2-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: mix compile
      - run: mix docs
      - run: mix hex.build
      - run: mix test
      - run: mix format --check-formatted
      - run: mix credo --ignore-checks "refactor"
      - run: mix dialyzer
      - save_cache:
          key: v2-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_15_otp_26:
    docker:
      - image: hexpm/elixir:1.15.2-erlang-26.0.2-alpine-3.18.2
    <<: *defaults
    steps:
      - <<: *install_system_deps
      - checkout
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_elixir_1_14_otp_25:
    docker:
      - image: hexpm/elixir:1.14.3-erlang-25.2.3-alpine-3.18.0
    <<: *defaults
    steps:
      - <<: *install_system_deps
      - checkout
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_elixir_1_13_otp_25:
    docker:
      - image: hexpm/elixir:1.13.4-erlang-25.3.2-alpine-3.18.0
    steps:
      - <<: *install_system_deps
      - checkout
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_elixir_1_12_otp_24:
    docker:
      - image: hexpm/elixir:1.12.1-erlang-24.0.2-alpine-3.13.3
    steps:
      - <<: *install_system_deps
      - checkout
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile

workflows:
  build_test:
    jobs:
      - build_elixir_1_17_otp_27
      - build_elixir_1_15_otp_26
      - build_elixir_1_14_otp_25
      - build_elixir_1_13_otp_25
      - build_elixir_1_12_otp_24
